remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Social Distance Pathfinder
description: Automatically finds the safest path for you to take given some footage.
logo: https://raw.githubusercontent.com/ThatAquarel/socialdistancepathfinder/main/docs/logo.jpg